apiVersion: v1
kind: Pod
metadata:
  name: print-date
  namespace: default
spec:
  containers:
    - name: main
      image: alpine
      args:
        - /bin/sh
        - -c
        - >
          while true;
          do
            date
            sleep 1
          done